// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKBAGaYYYEF7XoBxG-pl41fcHX7krVeQs',
    appId: '1:241658950818:web:eb90161579fe3300d4d3fb',
    messagingSenderId: '241658950818',
    projectId: 'smartshelf-4b145',
    authDomain: 'smartshelf-4b145.firebaseapp.com',
    storageBucket: 'smartshelf-4b145.firebasestorage.app',
    measurementId: 'G-C7YYTKFC11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdmQtatJQMdD406NuzU3jdn1_v62AtnmY',
    appId: '1:241658950818:android:d1abf17371b59c3ad4d3fb',
    messagingSenderId: '241658950818',
    projectId: 'smartshelf-4b145',
    storageBucket: 'smartshelf-4b145.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYrf-1mEMUUpQsu_JibLjAOOA1_RrUpgk',
    appId: '1:241658950818:ios:b4f9d3e765b9be21d4d3fb',
    messagingSenderId: '241658950818',
    projectId: 'smartshelf-4b145',
    storageBucket: 'smartshelf-4b145.firebasestorage.app',
    iosBundleId: 'com.smartshelf.smartShelf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYrf-1mEMUUpQsu_JibLjAOOA1_RrUpgk',
    appId: '1:241658950818:ios:b4f9d3e765b9be21d4d3fb',
    messagingSenderId: '241658950818',
    projectId: 'smartshelf-4b145',
    storageBucket: 'smartshelf-4b145.firebasestorage.app',
    iosBundleId: 'com.smartshelf.smartShelf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKBAGaYYYEF7XoBxG-pl41fcHX7krVeQs',
    appId: '1:241658950818:web:65a633ea5419f077d4d3fb',
    messagingSenderId: '241658950818',
    projectId: 'smartshelf-4b145',
    authDomain: 'smartshelf-4b145.firebaseapp.com',
    storageBucket: 'smartshelf-4b145.firebasestorage.app',
    measurementId: 'G-XMN0BE8W7M',
  );
}
